<tt>
I&#39;ve&nbsp;been&nbsp;doing&nbsp;some&nbsp;embedded&nbsp;python&nbsp;work&nbsp;and&nbsp;everything&nbsp;has&nbsp;been&nbsp;working&nbsp;like&nbsp;a&nbsp;charm&nbsp;thusfar!&nbsp;&nbsp;Twisted&nbsp;has&nbsp;saved&nbsp;us&nbsp;tons&nbsp;of&nbsp;work,&nbsp;hats&nbsp;off&nbsp;to&nbsp;the&nbsp;development&nbsp;team.&lt;div&gt;&lt;br&gt;&lt;/div&gt;&lt;div&gt;&lt;br&gt;&lt;/div&gt;&lt;div&gt;I&nbsp;have&nbsp;been&nbsp;having&nbsp;issues&nbsp;with&nbsp;shutting&nbsp;down&nbsp;twisted&nbsp;completely&nbsp;(I&nbsp;think).&nbsp;&nbsp;Even&nbsp;upon&nbsp;executing&nbsp;Py_Finalize&nbsp;or&nbsp;Py_EndInterpreter&nbsp;as&nbsp;necessary&nbsp;upon&nbsp;re-entering&nbsp;our&nbsp;browser&nbsp;plugin&nbsp;we&nbsp;hit&nbsp;an&nbsp;exception&nbsp;during&nbsp;twisted&nbsp;import.&lt;/div&gt;<br>
&lt;div&gt;&lt;br&gt;&lt;/div&gt;&lt;div&gt;&lt;br&gt;&lt;/div&gt;&lt;div&gt;Here&nbsp;is&nbsp;my&nbsp;traceback&nbsp;:&lt;/div&gt;&lt;div&gt;&lt;br&gt;&lt;/div&gt;&lt;div&gt;&lt;div&gt;Traceback&nbsp;(most&nbsp;recent&nbsp;call&nbsp;last):&lt;/div&gt;&lt;div&gt;&nbsp;&nbsp;File&nbsp;&quot;&lt;string&gt;&quot;,&nbsp;line&nbsp;1,&nbsp;in&nbsp;&lt;module&gt;&lt;/div&gt;&lt;div&gt;&nbsp;&nbsp;File&nbsp;&quot;ourCode.py&quot;,&nbsp;line&nbsp;8,&nbsp;in&nbsp;&lt;module&gt;&lt;/div&gt;<br>
&lt;div&gt;&nbsp;&nbsp;&nbsp;&nbsp;from&nbsp;twisted.spread&nbsp;import&nbsp;pb&lt;/div&gt;&lt;div&gt;&nbsp;&nbsp;File&nbsp;&quot;C:\Python25\lib\site-packages\twisted\spread\pb.py&quot;,&nbsp;line&nbsp;69,&nbsp;in&nbsp;&lt;module&gt;&lt;/div&gt;&lt;div&gt;&nbsp;&nbsp;&nbsp;&nbsp;from&nbsp;zope.interface&nbsp;import&nbsp;implements,&nbsp;Interface&lt;/div&gt;&lt;div&gt;&nbsp;&nbsp;File&nbsp;&quot;C:\Python25\lib\site-packages\zope\interface\__init__.py&quot;,&nbsp;line&nbsp;58,&nbsp;in&nbsp;&lt;module&gt;&lt;/div&gt;<br>
&lt;div&gt;&nbsp;&nbsp;&nbsp;&nbsp;_wire()&lt;/div&gt;&lt;div&gt;&nbsp;&nbsp;File&nbsp;&quot;C:\Python25\lib\site-packages\zope\interface\interface.py&quot;,&nbsp;line&nbsp;809,&nbsp;in&nbsp;_wire&lt;/div&gt;&lt;div&gt;&nbsp;&nbsp;&nbsp;&nbsp;classImplements(Attribute,&nbsp;IAttribute)&lt;/div&gt;&lt;div&gt;&nbsp;&nbsp;File&nbsp;&quot;C:\Python25\lib\site-packages\zope\interface\declarations.py&quot;,&nbsp;line&nbsp;461,&nbsp;in&nbsp;classImplements&lt;/div&gt;<br>
&lt;div&gt;&nbsp;&nbsp;&nbsp;&nbsp;spec&nbsp;=&nbsp;implementedBy(cls)&lt;/div&gt;&lt;div&gt;&nbsp;&nbsp;File&nbsp;&quot;C:\Python25\lib\site-packages\zope\interface\declarations.py&quot;,&nbsp;line&nbsp;332,&nbsp;in&nbsp;implementedByFallback&lt;/div&gt;&lt;div&gt;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;isinstance(spec,&nbsp;Implements):&lt;/div&gt;&lt;div&gt;TypeError:&nbsp;&#39;NoneType&#39;&nbsp;object&nbsp;is&nbsp;not&nbsp;callable&lt;/div&gt;<br>
&lt;div&gt;&lt;br&gt;&lt;/div&gt;&lt;div&gt;&lt;br&gt;&lt;/div&gt;&lt;div&gt;Changing&nbsp;the&nbsp;order&nbsp;of&nbsp;imports&nbsp;hasn&#39;t&nbsp;seemed&nbsp;to&nbsp;matter,&nbsp;looks&nbsp;to&nbsp;me&nbsp;like&nbsp;something&nbsp;in&nbsp;zope&nbsp;init&nbsp;blows&nbsp;up&nbsp;if&nbsp;it&#39;s&nbsp;already&nbsp;loaded.&lt;/div&gt;&lt;div&gt;&lt;br&gt;&lt;/div&gt;&lt;div&gt;Is&nbsp;there&nbsp;a&nbsp;safe&nbsp;way&nbsp;to&nbsp;make&nbsp;sure&nbsp;the&nbsp;threads&nbsp;are&nbsp;dead?&nbsp;&nbsp;To&nbsp;clean&nbsp;imports&nbsp;out?&nbsp;&nbsp;Anything?&nbsp;&nbsp;I&nbsp;haven&#39;t&nbsp;been&nbsp;able&nbsp;to&nbsp;find&nbsp;much&nbsp;documentation&nbsp;to&nbsp;help&nbsp;me&nbsp;overcome&nbsp;the&nbsp;problem&nbsp;and&nbsp;I&nbsp;CANNOT&nbsp;forcibly&nbsp;unload&nbsp;our&nbsp;app&nbsp;from&nbsp;browser&nbsp;memory.&lt;/div&gt;<br>
&lt;div&gt;&lt;br&gt;&lt;/div&gt;&lt;div&gt;If&nbsp;the&nbsp;C++&nbsp;code&nbsp;we&nbsp;are&nbsp;using&nbsp;for&nbsp;startup&nbsp;/&nbsp;shutdown&nbsp;let&nbsp;me&nbsp;know&nbsp;and&nbsp;I&nbsp;will&nbsp;post&nbsp;it&nbsp;as&nbsp;well.&lt;/div&gt;&lt;div&gt;&lt;br&gt;&lt;/div&gt;&lt;div&gt;&lt;br&gt;&lt;/div&gt;&lt;div&gt;Regards,&lt;/div&gt;&lt;div&gt;&lt;br&gt;&lt;/div&gt;&lt;div&gt;James&lt;/div&gt;&lt;div&gt;&lt;br&gt;&lt;/div&gt;&lt;/div&gt;<br>

</tt>
