<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<HTML>
 <HEAD>
   <TITLE> [Twisted-Python] Twisted plugins and py2exe
   </TITLE>
   <LINK REL="Index" HREF="index.html" >
   <LINK REL="made" HREF="mailto:twisted-python%40twistedmatrix.com?Subject=Re%3A%20%5BTwisted-Python%5D%20Twisted%20plugins%20and%20py2exe&In-Reply-To=%3C49A3D0A9.3040209%40arimaz.com%3E">
   <META NAME="robots" CONTENT="index,nofollow">
   <style type="text/css">
       pre {
           white-space: pre-wrap;       /* css-2.1, curent FF, Opera, Safari */
           }
   </style>
   <META http-equiv="Content-Type" content="text/html; charset=utf-8">
   <LINK REL="Previous"  HREF="051751.html">
   <LINK REL="Next"  HREF="051753.html">
 </HEAD>
 <BODY BGCOLOR="#ffffff">
   <H1>[Twisted-Python] Twisted plugins and py2exe</H1>
    <B>Gabriel Rossetti</B> 
    <A HREF="mailto:twisted-python%40twistedmatrix.com?Subject=Re%3A%20%5BTwisted-Python%5D%20Twisted%20plugins%20and%20py2exe&In-Reply-To=%3C49A3D0A9.3040209%40arimaz.com%3E"
       TITLE="[Twisted-Python] Twisted plugins and py2exe">gabriel.rossetti at arimaz.com
       </A><BR>
    <I>Tue Feb 24 03:49:13 MST 2009</I>
    <P><UL>
        <LI>Previous message (by thread): <A HREF="051751.html">[Twisted-Python] Twisted developers: please donate your time!
</A></li>
        <LI>Next message (by thread): <A HREF="051753.html">[Twisted-Python] Twisted plugins and py2exe
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#51752">[ date ]</a>
              <a href="thread.html#51752">[ thread ]</a>
              <a href="subject.html#51752">[ subject ]</a>
              <a href="author.html#51752">[ author ]</a>
         </LI>
       </UL>
    <HR>  
<!--beginarticle-->
<PRE>Hello everyone!

I used py2exe on a Twisted app of mine and I get this exception :


Traceback (most recent call last):
  File &quot;proj\service.pyc&quot;, line 1308, in connectionMade

  File &quot;proj\service.pyc&quot;, line 1640, in _register

  File &quot;proj\service.pyc&quot;, line 504, in loadPlugins

  File &quot;twisted\plugin.pyc&quot;, line 200, in getPlugins

--- &lt;exception caught here&gt; ---
  File &quot;twisted\plugin.pyc&quot;, line 179, in getCache

exceptions.AttributeError: ZipPath instance has no attribute 'setContent'

Has anyone ever had this problem while using plugins with Twisted and 
py2exe?

Thank you,
Gabriel


</PRE>

<!--endarticle-->
    <HR>
    <P><UL>
        <!--threads-->
	<LI>Previous message (by thread): <A HREF="051751.html">[Twisted-Python] Twisted developers: please donate your time!
</A></li>
	<LI>Next message (by thread): <A HREF="051753.html">[Twisted-Python] Twisted plugins and py2exe
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#51752">[ date ]</a>
              <a href="thread.html#51752">[ thread ]</a>
              <a href="subject.html#51752">[ subject ]</a>
              <a href="author.html#51752">[ author ]</a>
         </LI>
       </UL>

<hr>
<a href="https://twistedmatrix.com/cgi-bin/mailman/listinfo/twisted-python">More information about the Twisted-Python
mailing list</a><br>
</body></html>
