<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2//EN">
<HTML>
 <HEAD>
   <TITLE> [Twisted-Python] adbapi question
   </TITLE>
   <LINK REL="Index" HREF="index.html" >
   <LINK REL="made" HREF="mailto:twisted-python%40twistedmatrix.com?Subject=%5BTwisted-Python%5D%20adbapi%20question&In-Reply-To=3F74487A.8030309%40is.lg.ua">
   <META NAME="robots" CONTENT="index,nofollow">
   <META http-equiv="Content-Type" content="text/html; charset=us-ascii">
   <LINK REL="Previous"  HREF="005800.html">
   <LINK REL="Next"  HREF="005810.html">
 </HEAD>
 <BODY BGCOLOR="#ffffff">
   <H1>[Twisted-Python] adbapi question</H1>
    <B>Jp Calderone</B> 
    <A HREF="mailto:twisted-python%40twistedmatrix.com?Subject=%5BTwisted-Python%5D%20adbapi%20question&In-Reply-To=3F74487A.8030309%40is.lg.ua"
       TITLE="[Twisted-Python] adbapi question">exarkun at intarweb.us
       </A><BR>
    <I>Fri Sep 26 10:41:28 EDT 2003</I>
    <P><UL>
        <LI>Previous message: <A HREF="005800.html">[Twisted-Python] adbapi question
</A></li>
        <LI>Next message: <A HREF="005810.html">[Twisted-Python] Book on Twisted?
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#5801">[ date ]</a>
              <a href="thread.html#5801">[ thread ]</a>
              <a href="subject.html#5801">[ subject ]</a>
              <a href="author.html#5801">[ author ]</a>
         </LI>
       </UL>
    <HR>  
<!--beginarticle-->
<PRE>On Fri, Sep 26, 2003 at 05:08:58PM +0300, Ruslan Spivak wrote:
&gt;<i> [snip]
</I>&gt;<i> 
</I>&gt;<i> 
</I>&gt;<i> def dbClientFailed():
</I>&gt;<i>     print &quot;Failed!&quot;
</I>&gt;<i>     reactor.stop()
</I>&gt;<i> 
</I>&gt;<i> getClientsDBParams('alienoid').addCallbacks(dbClientSucceeded, 
</I>&gt;<i> dbClientFailed)
</I>&gt;<i> reactor.run()
</I>&gt;<i> 
</I>&gt;<i> 
</I>&gt;<i> The problem here is that when dbClientSucceeded is executed and i get 
</I>&gt;<i> &quot;no records&quot; - i don't get exception. Only when i press Ctrl + C on 
</I>&gt;<i> server i get those DBException. This code will be executed when remote 
</I>&gt;<i> client connects to server and i want those DBException be passed to 
</I>&gt;<i> remote client but i can't get it, can get it only with Ctrl + C
</I>&gt;<i> 
</I>&gt;<i> Your help is very appreciated.
</I>&gt;<i> Thanks in advance.
</I>
  Errbacks receive a single argument, the failure that caused them to be
caused.  Unfortunately, if you define your errback to take no arguments (as
you have), that error becomes a failure, which would pass on to the next
errback if it were registered, or, as in your code, would be silenced if
there are no more errbacks.

  Redefine dbClientFailed to take an argument and you should see the
behavior you expect.

  Jp
-------------- next part --------------
A non-text attachment was scrubbed...
Name: not available
Type: application/pgp-signature
Size: 189 bytes
Desc: not available
Url : <A HREF="http://twistedmatrix.com/pipermail/twisted-python/attachments/20030926/231548a7/attachment.pgp">http://twistedmatrix.com/pipermail/twisted-python/attachments/20030926/231548a7/attachment.pgp</A> 
</PRE>

<!--endarticle-->
    <HR>
    <P><UL>
        <!--threads-->
	<LI>Previous message: <A HREF="005800.html">[Twisted-Python] adbapi question
</A></li>
	<LI>Next message: <A HREF="005810.html">[Twisted-Python] Book on Twisted?
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#5801">[ date ]</a>
              <a href="thread.html#5801">[ thread ]</a>
              <a href="subject.html#5801">[ subject ]</a>
              <a href="author.html#5801">[ author ]</a>
         </LI>
       </UL>

<hr>
<a href="http://twistedmatrix.com/cgi-bin/mailman/listinfo/twisted-python">More information about the Twisted-Python
mailing list</a><br>
</body></html>
