<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2//EN">
<HTML>
 <HEAD>
   <TITLE> [Twisted-Python] Invalid 'reason' info - possible cause
   </TITLE>
   <LINK REL="Index" HREF="index.html" >
   <LINK REL="made" HREF="mailto:twisted-python%40twistedmatrix.com?Subject=%5BTwisted-Python%5D%20Invalid%20%27reason%27%20info%20-%20possible%20cause&In-Reply-To=20040520075635.40514.qmail%40web14806.mail.yahoo.com">
   <META NAME="robots" CONTENT="index,nofollow">
   <META http-equiv="Content-Type" content="text/html; charset=us-ascii">
   <LINK REL="Previous"  HREF="007843.html">
   <LINK REL="Next"  HREF="007849.html">
 </HEAD>
 <BODY BGCOLOR="#ffffff">
   <H1>[Twisted-Python] Invalid 'reason' info - possible cause</H1>
    <B>Itamar Shtull-Trauring</B> 
    <A HREF="mailto:twisted-python%40twistedmatrix.com?Subject=%5BTwisted-Python%5D%20Invalid%20%27reason%27%20info%20-%20possible%20cause&In-Reply-To=20040520075635.40514.qmail%40web14806.mail.yahoo.com"
       TITLE="[Twisted-Python] Invalid 'reason' info - possible cause">itamar at itamarst.org
       </A><BR>
    <I>Thu May 20 09:15:41 EDT 2004</I>
    <P><UL>
        <LI>Previous message: <A HREF="007843.html">[Twisted-Python] Invalid 'reason' info - possible cause
</A></li>
        <LI>Next message: <A HREF="007849.html">[Twisted-Python] Invalid 'reason' info - possible cause
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#7848">[ date ]</a>
              <a href="thread.html#7848">[ thread ]</a>
              <a href="subject.html#7848">[ subject ]</a>
              <a href="author.html#7848">[ author ]</a>
         </LI>
       </UL>
    <HR>  
<!--beginarticle-->
<PRE>On Thu, 2004-05-20 at 03:56, Sorin C. wrote:

&gt;<i> It seems that for every kind of selectable object -
</I>&gt;<i> even if not connected - it is issued connection lost.
</I>&gt;<i> I am unable at this moment to sugest a fix as I am not
</I>&gt;<i> familiar with the internals of twisted so I hope a
</I>&gt;<i> core developer can look into this further.
</I>
That is expected behaviour. If you shut down reactor, it closes all
connection by force, i.e. it is not a clean close. The problem is you
run reactor.stop() immediately before reactor.run(), so reactor shuts
down immediately.

-- 
Itamar Shtull-Trauring    <A HREF="http://itamarst.org">http://itamarst.org</A>




</PRE>

<!--endarticle-->
    <HR>
    <P><UL>
        <!--threads-->
	<LI>Previous message: <A HREF="007843.html">[Twisted-Python] Invalid 'reason' info - possible cause
</A></li>
	<LI>Next message: <A HREF="007849.html">[Twisted-Python] Invalid 'reason' info - possible cause
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#7848">[ date ]</a>
              <a href="thread.html#7848">[ thread ]</a>
              <a href="subject.html#7848">[ subject ]</a>
              <a href="author.html#7848">[ author ]</a>
         </LI>
       </UL>

<hr>
<a href="http://twistedmatrix.com/cgi-bin/mailman/listinfo/twisted-python">More information about the Twisted-Python
mailing list</a><br>
</body></html>
