<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<HTML>
 <HEAD>
   <TITLE> [Twisted-Python] Twisted logger changes
   </TITLE>
   <LINK REL="Index" HREF="index.html" >
   <LINK REL="made" HREF="mailto:twisted-python%40twistedmatrix.com?Subject=Re%3A%20%5BTwisted-Python%5D%20Twisted%20logger%20changes&In-Reply-To=%3CCAFUtXGyQRbLvpWs6wyj%3D1mdfjaB3VOvr-eMUx%2BkZsOYaxeBe2w%40mail.gmail.com%3E">
   <META NAME="robots" CONTENT="index,nofollow">
   <style type="text/css">
       pre {
           white-space: pre-wrap;       /* css-2.1, curent FF, Opera, Safari */
           }
   </style>
   <META http-equiv="Content-Type" content="text/html; charset=utf-8">
   
   
 </HEAD>
 <BODY BGCOLOR="#ffffff">
   <H1>[Twisted-Python] Twisted logger changes</H1>
    <B>Maciej Wasilak</B> 
    <A HREF="mailto:twisted-python%40twistedmatrix.com?Subject=Re%3A%20%5BTwisted-Python%5D%20Twisted%20logger%20changes&In-Reply-To=%3CCAFUtXGyQRbLvpWs6wyj%3D1mdfjaB3VOvr-eMUx%2BkZsOYaxeBe2w%40mail.gmail.com%3E"
       TITLE="[Twisted-Python] Twisted logger changes">wasilak at gmail.com
       </A><BR>
    <I>Mon Jun  8 10:51:33 MDT 2015</I>
    <P><UL>
        
        
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#62023">[ date ]</a>
              <a href="thread.html#62023">[ thread ]</a>
              <a href="subject.html#62023">[ subject ]</a>
              <a href="author.html#62023">[ author ]</a>
         </LI>
       </UL>
    <HR>  
<!--beginarticle-->
<PRE>Dear list,

I've tried running Twisted 15.2.1 with my old library, and I am
getting an exception, that I haven't seen before (with Twisted
14.0.0):

      File &quot;/usr/local/lib/python2.7/dist-packages/txthings/coap.py&quot;,
line 1338, in sendResponse
        print &quot;Token: %s&quot; % (response.token)
      File &quot;/usr/local/lib/python2.7/dist-packages/twisted/logger/_io.py&quot;,
line 163, in write
        string = string.decode(self._encoding)
      File &quot;/usr/lib/python2.7/encodings/utf_8.py&quot;, line 16, in decode
        return codecs.utf_8_decode(input, errors, True)
    exceptions.UnicodeDecodeError: 'utf8' codec can't decode byte 0xae
in position 7: invalid start byte

Although it is triggered by simple print, it seems to be caused by
logging. Does new logging framework need any configuration to stay
compatible with the old one?

Best regards
Maciej Wasilak


</PRE>
<!--endarticle-->
    <HR>
    <P><UL>
        <!--threads-->
	
	
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#62023">[ date ]</a>
              <a href="thread.html#62023">[ thread ]</a>
              <a href="subject.html#62023">[ subject ]</a>
              <a href="author.html#62023">[ author ]</a>
         </LI>
       </UL>

<hr>
<a href="https://twistedmatrix.com/cgi-bin/mailman/listinfo/twisted-python">More information about the Twisted-Python
mailing list</a><br>
</body></html>
