<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<HTML>
 <HEAD>
   <TITLE> [Twisted-Python] Trapping exceptions in Deferred
   </TITLE>
   <LINK REL="Index" HREF="index.html" >
   <LINK REL="made" HREF="mailto:twisted-python%40twistedmatrix.com?Subject=Re%3A%20%5BTwisted-Python%5D%20Trapping%20exceptions%20in%20Deferred&In-Reply-To=%3CFD55BD40-CDBA-41F8-90A4-AFBDCCF36EFC%40me.com%3E">
   <META NAME="robots" CONTENT="index,nofollow">
   <style type="text/css">
       pre {
           white-space: pre-wrap;       /* css-2.1, curent FF, Opera, Safari */
           }
   </style>
   <META http-equiv="Content-Type" content="text/html; charset=utf-8">
   <LINK REL="Previous"  HREF="061946.html">
   <LINK REL="Next"  HREF="061948.html">
 </HEAD>
 <BODY BGCOLOR="#ffffff">
   <H1>[Twisted-Python] Trapping exceptions in Deferred</H1>
    <B>Louis D. Burr</B> 
    <A HREF="mailto:twisted-python%40twistedmatrix.com?Subject=Re%3A%20%5BTwisted-Python%5D%20Trapping%20exceptions%20in%20Deferred&In-Reply-To=%3CFD55BD40-CDBA-41F8-90A4-AFBDCCF36EFC%40me.com%3E"
       TITLE="[Twisted-Python] Trapping exceptions in Deferred">ldanielburr at me.com
       </A><BR>
    <I>Tue May 12 11:38:51 MDT 2015</I>
    <P><UL>
        <LI>Previous message (by thread): <A HREF="061946.html">[Twisted-Python] Trapping exceptions in Deferred
</A></li>
        <LI>Next message (by thread): <A HREF="061948.html">[Twisted-Python] Trapping exceptions in Deferred
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#61947">[ date ]</a>
              <a href="thread.html#61947">[ thread ]</a>
              <a href="subject.html#61947">[ subject ]</a>
              <a href="author.html#61947">[ author ]</a>
         </LI>
       </UL>
    <HR>  
<!--beginarticle-->
<PRE>Hi Mashiat,

&gt;<i> On May 12, 2015, at 11:48 AM, Mashiat Sarker Shakkhar &lt;<A HREF="https://twistedmatrix.com/cgi-bin/mailman/listinfo/twisted-python">mashiat.sarker at gmail.com</A>&gt; wrote:
</I>&gt;<i> 
</I>[...]
&gt;<i> Alright. Below you can find a code snippet that is similar to my actual code. But my question is a little more generic - how do I catch exceptions that are encapsulated in a failure? If the actual exception is OpenSSL.SSL.Error, and it is wrapped in twisted.web._newclient.ResponseNeverReceived, how should my trap call look like?
</I>&gt;<i> 
</I>&gt;<i> ```
</I>&gt;<i> imort json
</I>&gt;<i> import StringIO
</I>&gt;<i> from twisted.internet import reactor
</I>&gt;<i> from twisted.internet.error import TimeoutError
</I>&gt;<i> from twisted.web._newclient import ResponseNeverReceived
</I>&gt;<i> from twisted.web.client import Agent, HTTPConnectionPool
</I>&gt;<i> from twisted.web.client import FileBodyProducer
</I>&gt;<i> 
</I>&gt;<i> def some_callback(response):
</I>&gt;<i>     pass
</I>&gt;<i> 
</I>&gt;<i> def log_ignore_network_errors(failure):
</I>&gt;<i>     print failure.getErrorMessage()
</I>&gt;<i>     failure.printTraceback()
</I>&gt;<i>     failure.trap(TimeoutError, ResponseNeverReceived)
</I>&gt;<i> 
</I>&gt;<i> agent = Agent(reactor)
</I>&gt;<i> body = FileBodyProducer(StringIO(json.dumps({'key': 'value'})))
</I>&gt;<i> d = agent.request('POST', '<A HREF="https://example.com">https://example.com</A> &lt;<A HREF="https://example.com/">https://example.com/</A>&gt;', Headers({'Content-Type': ['application/json']}), body)
</I>&gt;<i> d.addCallback(some_callback)
</I>&gt;<i> d.addErrback(log_ignore_network_errors)
</I>&gt;<i> ```
</I>
Thanks for providing the example.  Your code as presented here catches both TimeoutError and ResponseNeverReceived, so I am not sure why you think it isn’t working.  What are you seeing that indicates that the ResponseNeverReceived error is not being trapped?

As far as identifying/catching exceptions wrapped by ResponseNeverReceived, you can iterate over the “reasons” attribute (<A HREF="https://twistedmatrix.com/documents/current/api/twisted.web._newclient.ResponseNeverReceived.html">https://twistedmatrix.com/documents/current/api/twisted.web._newclient.ResponseNeverReceived.html</A> &lt;<A HREF="https://twistedmatrix.com/documents/current/api/twisted.web._newclient.ResponseNeverReceived.html">https://twistedmatrix.com/documents/current/api/twisted.web._newclient.ResponseNeverReceived.html</A>&gt;) and call either “trap” or “check” on each failure instance contained therein.

For any instance of twisted.python.failure, you can look at the “value” attribute to obtain the exception instance.

Hope this helps,

L. Daniel Burr

    
-------------- next part --------------
An HTML attachment was scrubbed...
URL: &lt;/pipermail/twisted-python/attachments/20150512/92e8dbad/attachment-0002.html&gt;
</PRE>

<!--endarticle-->
    <HR>
    <P><UL>
        <!--threads-->
	<LI>Previous message (by thread): <A HREF="061946.html">[Twisted-Python] Trapping exceptions in Deferred
</A></li>
	<LI>Next message (by thread): <A HREF="061948.html">[Twisted-Python] Trapping exceptions in Deferred
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#61947">[ date ]</a>
              <a href="thread.html#61947">[ thread ]</a>
              <a href="subject.html#61947">[ subject ]</a>
              <a href="author.html#61947">[ author ]</a>
         </LI>
       </UL>

<hr>
<a href="https://twistedmatrix.com/cgi-bin/mailman/listinfo/twisted-python">More information about the Twisted-Python
mailing list</a><br>
</body></html>
