<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2//EN">
<HTML>
 <HEAD>
   <TITLE> [Twisted-Python] &quot;_wait&quot; is blowing up?!
   </TITLE>
   <LINK REL="Index" HREF="index.html" >
   <LINK REL="made" HREF="mailto:twisted-python%40twistedmatrix.com?Subject=%5BTwisted-Python%5D%20%22_wait%22%20is%20blowing%20up%3F%21&In-Reply-To=">
   <META NAME="robots" CONTENT="index,nofollow">
   <META http-equiv="Content-Type" content="text/html; charset=us-ascii">
   <LINK REL="Previous"  HREF="018275.html">
   <LINK REL="Next"  HREF="018277.html">
 </HEAD>
 <BODY BGCOLOR="#ffffff">
   <H1>[Twisted-Python] &quot;_wait&quot; is blowing up?!</H1>
    <B>Brian Granger</B> 
    <A HREF="mailto:twisted-python%40twistedmatrix.com?Subject=%5BTwisted-Python%5D%20%22_wait%22%20is%20blowing%20up%3F%21&In-Reply-To="
       TITLE="[Twisted-Python] &quot;_wait&quot; is blowing up?!">ellisonbg.net at gmail.com
       </A><BR>
    <I>Sun Aug 24 02:25:01 EDT 2008</I>
    <P><UL>
        <LI>Previous message: <A HREF="018275.html">[Twisted-Python] Weekly Bug Summary
</A></li>
        <LI>Next message: <A HREF="018277.html">[Twisted-Python] &quot;_wait&quot; is blowing up?!
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#18276">[ date ]</a>
              <a href="thread.html#18276">[ thread ]</a>
              <a href="subject.html#18276">[ subject ]</a>
              <a href="author.html#18276">[ author ]</a>
         </LI>
       </UL>
    <HR>  
<!--beginarticle-->
<PRE>File &quot;/usr/lib/python2.5/site-packages/twisted/trial/unittest.py&quot;,
line 763, in run
   self._wait(d)
 File &quot;/usr/lib/python2.5/site-packages/twisted/trial/unittest.py&quot;,
line 901, in _wait
   reactor.run()
 File &quot;/usr/lib/python2.5/site-packages/twisted/internet/posixbase.py&quot;,
Hi,

We have a pretty big tests suite that uses trial to test all sorts of
twisted things.  We are pretty careful to do the right thing in our
tests and leave the reactor clean....but recently we began seeing a
transient really wierd bug when we run our test suite.

Some characteristics of the problem:

1.  The problem only appears sometimes - seems random
2.  The problem shows up in different test methods
3.  Sometimes it hangs the tests suite for a long time - eventually
twisted continues though

Here is the traceback we get.

line 220, in run
   self.mainLoop()
 File &quot;/usr/lib/python2.5/site-packages/twisted/internet/posixbase.py&quot;,
line 228, in mainLoop
   self.runUntilCurrent()
--- &lt;exception caught here&gt; ---
 File &quot;/usr/lib/python2.5/site-packages/twisted/internet/base.py&quot;,
line 533, in runUntilCurrent
   f(*a, **kw)
 File &quot;/usr/lib/python2.5/site-packages/twisted/internet/defer.py&quot;,
line 261, in errback
   self._startRunCallbacks(fail)
 File &quot;/usr/lib/python2.5/site-packages/twisted/internet/defer.py&quot;,
line 290, in _startRunCallbacks
   raise AlreadyCalledError
twisted.internet.defer.AlreadyCalledError:
ERROR

It appears that something is going on in the deadly _wait.  Any
thoughts on how we might fix this?

Thanks

Brian


</PRE>

<!--endarticle-->
    <HR>
    <P><UL>
        <!--threads-->
	<LI>Previous message: <A HREF="018275.html">[Twisted-Python] Weekly Bug Summary
</A></li>
	<LI>Next message: <A HREF="018277.html">[Twisted-Python] &quot;_wait&quot; is blowing up?!
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#18276">[ date ]</a>
              <a href="thread.html#18276">[ thread ]</a>
              <a href="subject.html#18276">[ subject ]</a>
              <a href="author.html#18276">[ author ]</a>
         </LI>
       </UL>

<hr>
<a href="http://twistedmatrix.com/cgi-bin/mailman/listinfo/twisted-python">More information about the Twisted-Python
mailing list</a><br>
</body></html>
