<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2//EN">
<HTML>
 <HEAD>
   <TITLE> [Twisted-Python] admin/runtests on OS X
   </TITLE>
   <LINK REL="Index" HREF="index.html" >
   <LINK REL="made" HREF="mailto:twisted-python%40twistedmatrix.com?Subject=%5BTwisted-Python%5D%20admin/runtests%20on%20OS%20X&In-Reply-To=">
   <META NAME="robots" CONTENT="index,nofollow">
   <META http-equiv="Content-Type" content="text/html; charset=us-ascii">
   <LINK REL="Previous"  HREF="002470.html">
   <LINK REL="Next"  HREF="002472.html">
 </HEAD>
 <BODY BGCOLOR="#ffffff">
   <H1>[Twisted-Python] admin/runtests on OS X</H1>
    <B>Bob Ippolito</B> 
    <A HREF="mailto:twisted-python%40twistedmatrix.com?Subject=%5BTwisted-Python%5D%20admin/runtests%20on%20OS%20X&In-Reply-To="
       TITLE="[Twisted-Python] admin/runtests on OS X">bob at redivi.com
       </A><BR>
    <I>Fri Dec 27 22:04:13 EST 2002</I>
    <P><UL>
        <LI>Previous message: <A HREF="002470.html">[Twisted-Python] twisted.names.dns
</A></li>
        <LI>Next message: <A HREF="002472.html">[Twisted-Python] twisted.web problem on FreeBSD 4.7
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#2471">[ date ]</a>
              <a href="thread.html#2471">[ thread ]</a>
              <a href="subject.html#2471">[ subject ]</a>
              <a href="author.html#2471">[ author ]</a>
         </LI>
       </UL>
    <HR>  
<!--beginarticle-->
<PRE>Just FYI on this one, as of now there's a lot less tests that fail on 
OS X 10.2.3 (Python 2.2).  All of the SSH stuff seems to have been 
resolved, just a few lingering failures elsewhere.. Itamar had 
mentioned that the rebuild failure was due to Python 2.2, I haven't 
looked into why the others fail.

======================================================================
ERROR: testNormalTermination 
(twisted.test.test_process.PosixProcessTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
   File &quot;/Users/bob/src/Twisted/twisted/test/test_process.py&quot;, line 207, 
in testNormalTermination
     p.reason.trap(error.ProcessDone)
   File &quot;/Users/bob/src/Twisted/twisted/python/failure.py&quot;, line 230, in 
trap
     raise self
Failure: [Failure instance: Traceback! 
twisted.internet.error.ProcessTerminated, process ended with exit code 1
]
======================================================================
ERROR: testReconnect (twisted.test.test_tcp.ConnectorTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
   File &quot;/Users/bob/src/Twisted/twisted/test/test_tcp.py&quot;, line 276, in 
testReconnect
     factory.reason.trap(error.ConnectionRefusedError)
   File &quot;/Users/bob/src/Twisted/twisted/python/failure.py&quot;, line 230, in 
trap
     raise self
Failure: [Failure instance: Traceback! 
twisted.internet.error.TimeoutError,
]
======================================================================
ERROR: testFailing (twisted.test.test_tcp.LoopbackTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
   File &quot;/Users/bob/src/Twisted/twisted/test/test_tcp.py&quot;, line 131, in 
testFailing
     clientF.reason.trap(error.ConnectionRefusedError)
   File &quot;/Users/bob/src/Twisted/twisted/python/failure.py&quot;, line 230, in 
trap
     raise self
Failure: [Failure instance: Traceback! 
twisted.internet.error.TimeoutError,
]
======================================================================
ERROR: testMessages (twisted.test.test_unix.UnixSocketTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
   File &quot;/Users/bob/src/Twisted/twisted/test/test_smtp.py&quot;, line 146, in 
testMessages
     self.loopback(protocol, clientProtocol)
   File &quot;/Users/bob/src/Twisted/twisted/test/test_unix.py&quot;, line 27, in 
loopback
     loopback.loopbackUNIX(client, server)
   File &quot;/Users/bob/src/Twisted/twisted/protocols/loopback.py&quot;, line 
132, in loopbackUNIX
     reactor.iterate()
   File &quot;/Users/bob/src/Twisted/twisted/internet/base.py&quot;, line 219, in 
iterate
     self.doIteration(delay)
--- &lt;exception caught here&gt; ---
   File &quot;/Users/bob/src/Twisted/twisted/internet/default.py&quot;, line 547, 
in doSelect
     why = getattr(selectable, method)()
   File &quot;/Users/bob/src/Twisted/twisted/internet/abstract.py&quot;, line 102, 
in doWrite
     self.unsent = self.unsent[l:]
exceptions.TypeError: sequence index must be integer
======================================================================
FAIL: testFileRebuild (twisted.test.test_rebuild.RebuildTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
   File &quot;/Users/bob/src/Twisted/twisted/test/test_rebuild.py&quot;, line 73, 
in testFileRebuild
     assert b.b() == 'c'
AssertionError
----------------------------------------------------------------------
Ran 369 tests in 92.723s

FAILED (failures=1, errors=4)



</PRE>

<!--endarticle-->
    <HR>
    <P><UL>
        <!--threads-->
	<LI>Previous message: <A HREF="002470.html">[Twisted-Python] twisted.names.dns
</A></li>
	<LI>Next message: <A HREF="002472.html">[Twisted-Python] twisted.web problem on FreeBSD 4.7
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#2471">[ date ]</a>
              <a href="thread.html#2471">[ thread ]</a>
              <a href="subject.html#2471">[ subject ]</a>
              <a href="author.html#2471">[ author ]</a>
         </LI>
       </UL>

<hr>
<a href="http://twistedmatrix.com/cgi-bin/mailman/listinfo/twisted-python">More information about the Twisted-Python
mailing list</a><br>
</body></html>
