<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<HTML>
 <HEAD>
   <TITLE> [Twisted-Python] safe_str is not safe
   </TITLE>
   <LINK REL="Index" HREF="index.html" >
   <LINK REL="made" HREF="mailto:twisted-python%40twistedmatrix.com?Subject=Re%3A%20%5BTwisted-Python%5D%20safe_str%20is%20not%20safe&In-Reply-To=%3C1955085.3s00IEhm95%40i5%3E">
   <META NAME="robots" CONTENT="index,nofollow">
   <style type="text/css">
       pre {
           white-space: pre-wrap;       /* css-2.1, curent FF, Opera, Safari */
           }
   </style>
   <META http-equiv="Content-Type" content="text/html; charset=utf-8">
   <LINK REL="Previous"  HREF="057732.html">
   <LINK REL="Next"  HREF="057659.html">
 </HEAD>
 <BODY BGCOLOR="#ffffff">
   <H1>[Twisted-Python] safe_str is not safe</H1>
    <B>Wolfgang Rohdewald</B> 
    <A HREF="mailto:twisted-python%40twistedmatrix.com?Subject=Re%3A%20%5BTwisted-Python%5D%20safe_str%20is%20not%20safe&In-Reply-To=%3C1955085.3s00IEhm95%40i5%3E"
       TITLE="[Twisted-Python] safe_str is not safe">wolfgang at rohdewald.de
       </A><BR>
    <I>Mon Feb  6 14:29:26 MST 2012</I>
    <P><UL>
        <LI>Previous message (by thread): <A HREF="057732.html">[Twisted-Python] CopyableFailure fails
</A></li>
        <LI>Next message (by thread): <A HREF="057659.html">[Twisted-Python] How to Control Twisted Program through CLI
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#57655">[ date ]</a>
              <a href="thread.html#57655">[ thread ]</a>
              <a href="subject.html#57655">[ subject ]</a>
              <a href="author.html#57655">[ author ]</a>
         </LI>
       </UL>
    <HR>  
<!--beginarticle-->
<PRE>after patching CopyableFailure as written,

the stack trace now ends with the following lines. The correct
exception message is still not shown. It contains unicode chars
which reflect.py/safe_str cannot handle.

  File &quot;/hdd/pub/src/gitgames/kajongg/src/scoringengine.py&quot;, line 170, in 
initRuleset
    raise Exception(m18n('ruleset &quot;%1&quot; not found', self.name))
exceptions.Exception: &lt;Exception instance at 0x30e8b48 with str error:
 'Traceback (most recent call last):\n  File &quot;/usr/local/lib/python2.7/dist-
packages/Twisted-11.0.0-py2.7-linux-x86_64.egg/twisted/python/reflect.py&quot;, line 
546, in _safeFormat\n    return formatter(o)\nUnicodeEncodeError: \'ascii\' 
codec can\'t encode character u\'\\u201e\' in position 10: ordinal not in 
range(128)\n'&gt;
Unhandled error in Deferred:


after replacing safe_str by safe_repr in twisted/python/failure.py,

I finally get a meaningful printout:
  File &quot;/hdd/pub/src/gitgames/kajongg/src/scoringengine.py&quot;, line 170, in 
initRuleset
    raise Exception(m18n('ruleset &quot;%1&quot; not found', self.name))
exceptions.Exception: Exception(u'Regelsatz 
\u201e55a8a17e29a1a087cc8df9cedb5590cd\u201c nicht gefunden',)
Unhandled error in Deferred:

of course a correct encoding would be even better...
my patch:

--- failure.org 2012-02-06 22:22:46.395065076 +0100
+++ failure.py  2012-02-06 22:22:51.259064816 +0100
@@ -472,7 +472,7 @@
         &quot;&quot;&quot;Get a string of the exception which caused this Failure.&quot;&quot;&quot;
         if isinstance(self.value, Failure):
             return self.value.getErrorMessage()
-        return reflect.safe_str(self.value)
+        return reflect.safe_repr(self.value)
 
     def getBriefTraceback(self):
         io = StringIO()
@@ -517,7 +517,7 @@
             w(&quot;%s: %s: %s\n&quot; % (
                     hasFrames,
                     reflect.safe_str(self.type),
-                    reflect.safe_str(self.value)))
+                    reflect.safe_repr(self.value)))
         else:
             w( 'Traceback (most recent call last):\n')
 
@@ -542,7 +542,7 @@
                 w(self.type + &quot;\n&quot;)
             else:
                 w(&quot;%s: %s\n&quot; % (reflect.qual(self.type),
-                                reflect.safe_str(self.value)))
+                                reflect.safe_repr(self.value)))
         # chaining
         if isinstance(self.value, Failure):
             # TODO: indentation for chained failures?

-- 
Wolfgang


</PRE>

<!--endarticle-->
    <HR>
    <P><UL>
        <!--threads-->
	<LI>Previous message (by thread): <A HREF="057732.html">[Twisted-Python] CopyableFailure fails
</A></li>
	<LI>Next message (by thread): <A HREF="057659.html">[Twisted-Python] How to Control Twisted Program through CLI
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#57655">[ date ]</a>
              <a href="thread.html#57655">[ thread ]</a>
              <a href="subject.html#57655">[ subject ]</a>
              <a href="author.html#57655">[ author ]</a>
         </LI>
       </UL>

<hr>
<a href="https://twistedmatrix.com/cgi-bin/mailman/listinfo/twisted-python">More information about the Twisted-Python
mailing list</a><br>
</body></html>
