Traceback (most recent call last):
  File "/sw/lib/python2.2/site-packages/twisted/web/server.py", line 162, in render
    body = resrc.render(self)
  File "/sw/lib/python2.2/site-packages/twisted/web/woven/controller.py", line 202, in render
    return self.renderView(request)
  File "/sw/lib/python2.2/site-packages/twisted/web/woven/page.py", line 46, in renderView
    doneCallback=self.gatheredControllers)
  File "/sw/lib/python2.2/site-packages/twisted/web/woven/view.py", line 178, in render
    self.handleDocument(request, self.d)
--- <exception caught here> ---
  File "/sw/lib/python2.2/site-packages/twisted/web/woven/view.py", line 245, in handleDocument
    self.handleOutstanding(request)
  File "/sw/lib/python2.2/site-packages/twisted/web/woven/view.py", line 263, in handleOutstanding
    self.handleNode(request, node)
  File "/sw/lib/python2.2/site-packages/twisted/web/woven/view.py", line 563, in handleNode
    returnNode = self.dispatchResult(request, node, view)
  File "/sw/lib/python2.2/site-packages/twisted/web/woven/view.py", line 290, in dispatchResult
    result = adapter.generate(request, node)
  File "/sw/lib/python2.2/site-packages/twisted/web/woven/view.py", line 697, in generate
    newNode = self.data.generate(request, node)
  File "/sw/lib/python2.2/site-packages/twisted/web/woven/widgets.py", line 198, in generate
    data = self.getData(request)
  File "/sw/lib/python2.2/site-packages/twisted/web/woven/widgets.py", line 140, in getData
    return self.model.getData(request)
exceptions.TypeError: getData() takes exactly 1 argument (2 given)
