<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2//EN">
<HTML>
 <HEAD>
   <TITLE> [Twisted-Python] Re: twisted-names: Cryptic error with no	traceback?
   </TITLE>
   <LINK REL="Index" HREF="index.html" >
   <LINK REL="made" HREF="mailto:twisted-python%40twistedmatrix.com?Subject=%5BTwisted-Python%5D%20Re%3A%20twisted-names%3A%20Cryptic%20error%20with%20no%0A%09traceback%3F&In-Reply-To=8e5b27790702271218r72d25f2dp8f88410e32a015cd%40mail.gmail.com">
   <META NAME="robots" CONTENT="index,nofollow">
   <META http-equiv="Content-Type" content="text/html; charset=us-ascii">
   <LINK REL="Previous"  HREF="014902.html">
   <LINK REL="Next"  HREF="014904.html">
 </HEAD>
 <BODY BGCOLOR="#ffffff">
   <H1>[Twisted-Python] Re: twisted-names: Cryptic error with no	traceback?</H1>
    <B>Jean-Paul Calderone</B> 
    <A HREF="mailto:twisted-python%40twistedmatrix.com?Subject=%5BTwisted-Python%5D%20Re%3A%20twisted-names%3A%20Cryptic%20error%20with%20no%0A%09traceback%3F&In-Reply-To=8e5b27790702271218r72d25f2dp8f88410e32a015cd%40mail.gmail.com"
       TITLE="[Twisted-Python] Re: twisted-names: Cryptic error with no	traceback?">exarkun at divmod.com
       </A><BR>
    <I>Tue Feb 27 20:07:17 EST 2007</I>
    <P><UL>
        <LI>Previous message: <A HREF="014902.html">[Twisted-Python] Re: twisted-names: Cryptic error with no traceback?
</A></li>
        <LI>Next message: <A HREF="014904.html">[Twisted-Python] Re: twisted-names: Cryptic error with no	traceback?
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#14903">[ date ]</a>
              <a href="thread.html#14903">[ thread ]</a>
              <a href="subject.html#14903">[ subject ]</a>
              <a href="author.html#14903">[ author ]</a>
         </LI>
       </UL>
    <HR>  
<!--beginarticle-->
<PRE>On Tue, 27 Feb 2007 15:18:26 -0500, Paul Marks &lt;<A HREF="http://twistedmatrix.com/cgi-bin/mailman/listinfo/twisted-python">pmarks at purdue.edu</A>&gt; wrote:
&gt;<i>On 2/27/07, Paul Marks &lt;<A HREF="http://twistedmatrix.com/cgi-bin/mailman/listinfo/twisted-python">pmarks at purdue.edu</A>&gt; wrote:
</I>&gt;&gt;<i>Some users of a program that I'm writing have been reporting this
</I>&gt;&gt;<i>error that I so far have been unable to track down.  It seems that it
</I>&gt;&gt;<i>originates from Twisted, but that it skips around my errback handler,
</I>&gt;&gt;<i>and provides no traceback information:
</I>&gt;&gt;<i>
</I>&gt;&gt;<i>       Traceback (most recent call last):
</I>&gt;&gt;<i>       Failure: twisted.names.error.DNSQueryTimeoutError:
</I>&gt;&gt;<i>
</I>&gt;&gt;<i>
</I>&gt;&gt;<i>My query is made from line 121 here:
</I>&gt;&gt;<i><A HREF="http://dtella.svn.sourceforge.net/viewvc/dtella/tags/1.0.2/dtella_dnslookup.py?revision=406&amp;view=markup">http://dtella.svn.sourceforge.net/viewvc/dtella/tags/1.0.2/dtella_dnslookup.py?revision=406&amp;view=markup</A>
</I>&gt;&gt;<i>
</I>&gt;&gt;<i>Does anyone have any insight as to where this error could be coming
</I>&gt;&gt;<i>from, and why it isn't getting trapped by my errback function?  I
</I>&gt;&gt;<i>don't know yet whether this is a problem in Twisted, or if I'm doing
</I>&gt;&gt;<i>something incorrect in my err_cb.
</I>&gt;<i>
</I>&gt;<i>Update:
</I>&gt;<i>Yay, I finally found the bug!  Turns out it's a problem in Twisted.
</I>&gt;<i>
</I>&gt;<i>Inside DNSDatagramProtocol.writeMessage, it writes to the UDP socket,
</I>&gt;<i>and never checks for socket.error.
</I>&gt;<i>
</I>&gt;<i>If a socket.error does occur, then the query() function blows up
</I>&gt;<i>instead of returning its deferred.  So, cancelCall gets forgotten.  A
</I>&gt;<i>few seconds later, it chucks a DNSQueryTimeoutError, and the deferred
</I>&gt;<i>gets garbage collected without anything handling it.
</I>
What socket.error are you seeing?

Jean-Paul


</PRE>

<!--endarticle-->
    <HR>
    <P><UL>
        <!--threads-->
	<LI>Previous message: <A HREF="014902.html">[Twisted-Python] Re: twisted-names: Cryptic error with no traceback?
</A></li>
	<LI>Next message: <A HREF="014904.html">[Twisted-Python] Re: twisted-names: Cryptic error with no	traceback?
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#14903">[ date ]</a>
              <a href="thread.html#14903">[ thread ]</a>
              <a href="subject.html#14903">[ subject ]</a>
              <a href="author.html#14903">[ author ]</a>
         </LI>
       </UL>

<hr>
<a href="http://twistedmatrix.com/cgi-bin/mailman/listinfo/twisted-python">More information about the Twisted-Python
mailing list</a><br>
</body></html>
