<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2//EN">
<HTML>
 <HEAD>
   <TITLE> [Twisted-Python] Twisted server connection loss with Mysql
   </TITLE>
   <LINK REL="Index" HREF="index.html" >
   <LINK REL="made" HREF="mailto:twisted-python%40twistedmatrix.com?Subject=%5BTwisted-Python%5D%20Twisted%20server%20connection%20loss%20with%20Mysql&In-Reply-To=056E50A3-19A1-4BA4-B0FA-17DFB388DB50%40fuhm.net">
   <META NAME="robots" CONTENT="index,nofollow">
   <META http-equiv="Content-Type" content="text/html; charset=us-ascii">
   <LINK REL="Previous"  HREF="010634.html">
   <LINK REL="Next"  HREF="010633.html">
 </HEAD>
 <BODY BGCOLOR="#ffffff">
   <H1>[Twisted-Python] Twisted server connection loss with Mysql</H1>
    <B>Dave Peticolas</B> 
    <A HREF="mailto:twisted-python%40twistedmatrix.com?Subject=%5BTwisted-Python%5D%20Twisted%20server%20connection%20loss%20with%20Mysql&In-Reply-To=056E50A3-19A1-4BA4-B0FA-17DFB388DB50%40fuhm.net"
       TITLE="[Twisted-Python] Twisted server connection loss with Mysql">dave at krondo.com
       </A><BR>
    <I>Thu Jun  2 21:54:12 EDT 2005</I>
    <P><UL>
        <LI>Previous message: <A HREF="010634.html">[Twisted-Python] Twisted server connection loss with Mysql  
</A></li>
        <LI>Next message: <A HREF="010633.html">[Twisted-Python] Twisted server connection loss with Mysql
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#10642">[ date ]</a>
              <a href="thread.html#10642">[ thread ]</a>
              <a href="subject.html#10642">[ subject ]</a>
              <a href="author.html#10642">[ author ]</a>
         </LI>
       </UL>
    <HR>  
<!--beginarticle-->
<PRE>On Thu, 2005-06-02 at 14:20 -0400, James Y Knight wrote:
&gt;<i> On Jun 2, 2005, at 8:47 AM, Raghul Jagan wrote:
</I>&gt;<i> &gt;          I also tried using the &quot;cp_reconnect=1&quot; for my twisted  
</I>&gt;<i> &gt; server.The first time it works but  the same error ocurrs after  
</I>&gt;<i> &gt; that .Is there anyway to solve this problem? I also tried by  
</I>&gt;<i> &gt; changing the value &quot;reconnect=True&quot; in adbapi.py file,the same  
</I>&gt;<i> &gt; error occurs what will be my problem? My machine configuration is
</I>&gt;<i> 
</I>&gt;<i> The expected behavior of cp_reconnect is not to retry the query  
</I>&gt;<i> automatically if it fails, because doing so could have undefined  
</I>&gt;<i> consequences. Really, it probably could retry when the error was on  
</I>&gt;<i> the query, not on the commit, but it doesn't currently.
</I>&gt;<i> 
</I>&gt;<i> If you have a connection pool size of 10, expect to see 10 queries  
</I>&gt;<i> fail before everything's working perfectly again, as each thread  
</I>&gt;<i> notices its connection has died (after failing to make the query) and  
</I>&gt;<i> closes it. In your app, you can either catch ConnectionLost errors  
</I>&gt;<i> and retry the queries yourself or live with 10 queries failing after  
</I>&gt;<i> restarting the database.
</I>
Unfortunately, mysqldb doesn't throw an exception when you call
cursor() on a closed connection so the exception doesn't happen
until the query itself. Adding an option to adbapi to retry queries
on a failed connection shouldn't be too hard, I'll add that to the
tracker.

dave




</PRE>

<!--endarticle-->
    <HR>
    <P><UL>
        <!--threads-->
	<LI>Previous message: <A HREF="010634.html">[Twisted-Python] Twisted server connection loss with Mysql  
</A></li>
	<LI>Next message: <A HREF="010633.html">[Twisted-Python] Twisted server connection loss with Mysql
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#10642">[ date ]</a>
              <a href="thread.html#10642">[ thread ]</a>
              <a href="subject.html#10642">[ subject ]</a>
              <a href="author.html#10642">[ author ]</a>
         </LI>
       </UL>

<hr>
<a href="http://twistedmatrix.com/cgi-bin/mailman/listinfo/twisted-python">More information about the Twisted-Python
mailing list</a><br>
</body></html>
